from typing import List, Dict, Any

SEED_USERS: List[Dict[str, Any]] = [
    {
        "user_id": "USR-ADMIN-01",
        "name": "Prof. S. K. Mehta",
        "email": "admin@campus.edu",
        "password_hash": "admin123",
        "role": "ADMIN",
        "student_id": "ADMIN-001",
        "department": "Proctorial Board / Security",
        "semester": "Staff",
        "phone": "+91 9876543299",
        "created_at": "2026-09-01T09:00:00"
    },
    {
        "user_id": "USR-STUDENT-01",
        "name": "Rahul Sharma",
        "email": "rahul.sharma@campus.edu",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100045",
        "department": "Computer Science & Engineering",
        "semester": "Semester 3",
        "phone": "+91 9876543210",
        "created_at": "2026-10-01T10:00:00"
    },
    {
        "user_id": "USR-STUDENT-02",
        "name": "Priya Verma",
        "email": "priya.verma@campus.edu",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100088",
        "department": "Information Technology",
        "semester": "Semester 3",
        "phone": "+91 9876543211",
        "created_at": "2026-10-02T11:30:00"
    },
    {
        "user_id": "USR-STUDENT-03",
        "name": "Aman Gupta",
        "email": "aman.gupta@campus.edu",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100112",
        "department": "Electronics & Communication",
        "semester": "Semester 5",
        "phone": "+91 9876543212",
        "created_at": "2026-10-03T12:00:00"
    }
]

SEED_IOT_BOXES: List[Dict[str, Any]] = [
    {
        "box_id": "BOX-001",
        "name": "Central Library Smart Drop Box",
        "location": "Library",
        "status": "ONLINE",
        "last_seen": "2026-10-07T12:28:00",
        "items_registered": 12,
        "created_at": "2026-09-15T08:00:00"
    },
    {
        "box_id": "BOX-002",
        "name": "Student Canteen Smart Box",
        "location": "Canteen",
        "status": "ONLINE",
        "last_seen": "2026-10-07T12:25:00",
        "items_registered": 5,
        "created_at": "2026-09-20T08:00:00"
    }
]

# 10 Realistic Lost Items
SEED_LOST_ITEMS: List[Dict[str, Any]] = [
    {
        "item_id": "LOST-0001",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@campus.edu",
        "student_id": "2300970100045",
        "item_name": "Leather Wallet with College ID",
        "category": "Wallet",
        "brand": "Wildhorn",
        "color": "Black",
        "description": "Black leather wallet with college ID lost near library reading room.",
        "location": "Library",
        "lost_at": "2026-10-06T13:30:00",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        "status": "LOST",
        "created_at": "2026-10-06T14:00:00"
    },
    {
        "item_id": "LOST-0002",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@campus.edu",
        "student_id": "2300970100088",
        "item_name": "Wireless Earbuds",
        "category": "Electronics",
        "brand": "Boat",
        "color": "White",
        "description": "White wireless earbuds inside a black silicone protective case. Lost on 1st floor desk.",
        "location": "Library",
        "lost_at": "2026-10-05T14:30:00",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
        "status": "LOST",
        "created_at": "2026-10-05T15:00:00"
    },
    {
        "item_id": "LOST-0003",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@campus.edu",
        "student_id": "2300970100112",
        "item_name": "Scientific Calculator",
        "category": "Electronics",
        "brand": "Casio",
        "color": "Black",
        "description": "Casio FX-991EX ClassWiz scientific calculator with name written in marker on back.",
        "location": "Admin Block",
        "lost_at": "2026-10-04T11:00:00",
        "image_url": "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400",
        "status": "LOST",
        "created_at": "2026-10-04T11:30:00"
    },
    {
        "item_id": "LOST-0004",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@campus.edu",
        "student_id": "2300970100045",
        "item_name": "Bike Keychain with 3 Keys",
        "category": "Keys",
        "brand": "Royal Enfield",
        "color": "Silver",
        "description": "Set of 3 keys with a black Royal Enfield leather keychain and mini carabiner clip.",
        "location": "Canteen",
        "lost_at": "2026-10-03T16:00:00",
        "image_url": "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=400",
        "status": "LOST",
        "created_at": "2026-10-03T16:30:00"
    },
    {
        "item_id": "LOST-0005",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@campus.edu",
        "student_id": "2300970100088",
        "item_name": "Stainless Steel Water Bottle",
        "category": "Bottle",
        "brand": "Milton",
        "color": "Blue",
        "description": "Milton 1000ml blue thermosteel insulated water bottle with stickers.",
        "location": "Sports Complex",
        "lost_at": "2026-10-02T17:30:00",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        "status": "LOST",
        "created_at": "2026-10-02T18:00:00"
    },
    {
        "item_id": "LOST-0006",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@campus.edu",
        "student_id": "2300970100112",
        "item_name": "Smart Fitness Band",
        "category": "Watch",
        "brand": "Noise",
        "color": "Black",
        "description": "Noise ColorFit Pulse smart watch with black silicon strap.",
        "location": "Sports Complex",
        "lost_at": "2026-10-01T08:30:00",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        "status": "LOST",
        "created_at": "2026-10-01T09:00:00"
    },
    {
        "item_id": "LOST-0007",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@campus.edu",
        "student_id": "2300970100045",
        "item_name": "Student Identity Card & Lanyard",
        "category": "ID Card",
        "brand": "Campus ID",
        "color": "Blue",
        "description": "Blue lanyard with college identity card of Rahul Sharma (Roll: 2300970100045).",
        "location": "Main Gate",
        "lost_at": "2026-09-30T09:15:00",
        "image_url": "https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=400",
        "status": "LOST",
        "created_at": "2026-09-30T09:45:00"
    },
    {
        "item_id": "LOST-0008",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@campus.edu",
        "student_id": "2300970100088",
        "item_name": "Laptop Backpack",
        "category": "Bag",
        "brand": "Skybags",
        "color": "Grey",
        "description": "Grey Skybags waterproof laptop bag containing notebook and pen drive.",
        "location": "Classroom Hall",
        "lost_at": "2026-09-29T15:00:00",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "status": "LOST",
        "created_at": "2026-09-29T15:30:00"
    },
    {
        "item_id": "LOST-0009",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@campus.edu",
        "student_id": "2300970100112",
        "item_name": "64GB SanDisk USB Flash Drive",
        "category": "Electronics",
        "brand": "SanDisk",
        "color": "Red",
        "description": "Red SanDisk Ultra Dual Drive USB 3.0 containing semester 3 project code and lab files.",
        "location": "Library",
        "lost_at": "2026-09-28T14:00:00",
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400",
        "status": "LOST",
        "created_at": "2026-09-28T14:30:00"
    },
    {
        "item_id": "LOST-0010",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@campus.edu",
        "student_id": "2300970100045",
        "item_name": "Data Structures & Algorithms Textbook",
        "category": "Books",
        "brand": "Pearson",
        "color": "Blue",
        "description": "Introduction to Algorithms (CLRS 3rd Edition) paperback book with yellow sticky notes.",
        "location": "Library",
        "lost_at": "2026-09-27T17:00:00",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        "status": "LOST",
        "created_at": "2026-09-27T17:30:00"
    }
]

# 10 Realistic Found Items (Including exact matches with lost items)
SEED_FOUND_ITEMS: List[Dict[str, Any]] = [
    {
        "item_id": "FOUND-0001",
        "rfid_id": "RFID-1024",
        "box_id": "BOX-001",
        "item_name": "Black Leather Wallet",
        "category": "Wallet",
        "brand": "Wildhorn",
        "color": "Black",
        "description": "Black leather wallet containing college identity card found near library reading table.",
        "location": "Library",
        "found_at": "2026-10-06T14:15:00",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-001 (Library)",
        "status": "FOUND",
        "created_at": "2026-10-06T14:15:00"
    },
    {
        "item_id": "FOUND-0002",
        "rfid_id": "RFID-E204A1",
        "box_id": "BOX-001",
        "item_name": "Boat Earbuds in Silicone Case",
        "category": "Electronics",
        "brand": "Boat",
        "color": "White",
        "description": "White Boat Airdopes wireless earbuds inside black silicone case discovered on 1st floor reading desk.",
        "location": "Library",
        "found_at": "2026-10-05T15:10:00",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-001 (Library)",
        "status": "FOUND",
        "created_at": "2026-10-05T15:10:00"
    },
    {
        "item_id": "FOUND-0003",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Casio Scientific Calculator FX-991EX",
        "category": "Electronics",
        "brand": "Casio",
        "color": "Black",
        "description": "Casio FX991EX ClassWiz scientific calculator found in room 204 admin block.",
        "location": "Admin Block",
        "found_at": "2026-10-04T12:00:00",
        "image_url": "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-02",
        "reported_by_name": "Priya Verma",
        "status": "FOUND",
        "created_at": "2026-10-04T12:00:00"
    },
    {
        "item_id": "FOUND-0004",
        "rfid_id": "RFID-KEY-88",
        "box_id": "BOX-002",
        "item_name": "Bike Keys with Leather Tag",
        "category": "Keys",
        "brand": "Royal Enfield",
        "color": "Silver",
        "description": "Three metal keys on a Royal Enfield branded leather strap found at canteen table.",
        "location": "Canteen",
        "found_at": "2026-10-03T16:45:00",
        "image_url": "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-002 (Canteen)",
        "status": "FOUND",
        "created_at": "2026-10-03T16:45:00"
    },
    {
        "item_id": "FOUND-0005",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Blue Insulated Bottle",
        "category": "Bottle",
        "brand": "Milton",
        "color": "Blue",
        "description": "Milton blue steel thermos water bottle found in badminton court seating bench.",
        "location": "Sports Complex",
        "found_at": "2026-10-02T18:15:00",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-01",
        "reported_by_name": "Rahul Sharma",
        "status": "FOUND",
        "created_at": "2026-10-02T18:15:00"
    },
    {
        "item_id": "FOUND-0006",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Black Fitness Smartwatch",
        "category": "Watch",
        "brand": "Noise",
        "color": "Black",
        "description": "Noise ColorFit Pulse black digital fitness band found on gym floor.",
        "location": "Sports Complex",
        "found_at": "2026-10-01T09:30:00",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-03",
        "reported_by_name": "Aman Gupta",
        "status": "FOUND",
        "created_at": "2026-10-01T09:30:00"
    },
    {
        "item_id": "FOUND-0007",
        "rfid_id": None,
        "box_id": None,
        "item_name": "College ID Badge with Blue Lanyard",
        "category": "ID Card",
        "brand": "Campus ID",
        "color": "Blue",
        "description": "Student identity card on blue strap dropped near security cabin at main gate.",
        "location": "Main Gate",
        "found_at": "2026-09-30T10:00:00",
        "image_url": "https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Security Desk",
        "status": "FOUND",
        "created_at": "2026-09-30T10:00:00"
    },
    {
        "item_id": "FOUND-0008",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Grey Laptop Bag",
        "category": "Bag",
        "brand": "Skybags",
        "color": "Grey",
        "description": "Skybags grey backpack found on desk row 3 in lecture hall 102.",
        "location": "Classroom Hall",
        "found_at": "2026-09-29T16:00:00",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-02",
        "reported_by_name": "Priya Verma",
        "status": "FOUND",
        "created_at": "2026-09-29T16:00:00"
    },
    {
        "item_id": "FOUND-0009",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Red 64GB Flash Drive",
        "category": "Electronics",
        "brand": "SanDisk",
        "color": "Red",
        "description": "SanDisk Dual USB pendrive plugged into library computer terminal 8.",
        "location": "Library",
        "found_at": "2026-09-28T15:00:00",
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Librarian Desk",
        "status": "FOUND",
        "created_at": "2026-09-28T15:00:00"
    },
    {
        "item_id": "FOUND-0010",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Algorithms Computer Science Textbook",
        "category": "Books",
        "brand": "Pearson",
        "color": "Blue",
        "description": "Introduction to Algorithms book found on 2nd floor library table.",
        "location": "Library",
        "found_at": "2026-09-27T18:00:00",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Library Staff",
        "status": "FOUND",
        "created_at": "2026-09-27T18:00:00"
    }
]

SEED_CLAIMS: List[Dict[str, Any]] = [
    {
        "claim_id": "CLM-001",
        "user_id": "USR-STUDENT-01",
        "student_name": "Rahul Sharma",
        "student_email": "rahul.sharma@campus.edu",
        "student_id": "2300970100045",
        "lost_item_id": "LOST-0001",
        "found_item_id": "FOUND-0001",
        "item_name": "Black Leather Wallet",
        "answers": "Contains student ID with roll 2300970100045, one metro card, and ₹350 cash inside coin pocket.",
        "status": "PENDING",
        "admin_notes": None,
        "created_at": "2026-10-06T15:00:00",
        "reviewed_at": None
    },
    {
        "claim_id": "CLM-002",
        "user_id": "USR-STUDENT-02",
        "student_name": "Priya Verma",
        "student_email": "priya.verma@campus.edu",
        "student_id": "2300970100088",
        "lost_item_id": "LOST-0002",
        "found_item_id": "FOUND-0002",
        "item_name": "Wireless Earbuds",
        "answers": "Small cat sticker on top of the black silicone case, serial starts with BT-88.",
        "status": "PENDING",
        "admin_notes": None,
        "created_at": "2026-10-05T16:00:00",
        "reviewed_at": None
    },
    {
        "claim_id": "CLM-003",
        "user_id": "USR-STUDENT-03",
        "student_name": "Aman Gupta",
        "student_email": "aman.gupta@campus.edu",
        "student_id": "2300970100112",
        "lost_item_id": "LOST-0003",
        "found_item_id": "FOUND-0003",
        "item_name": "Scientific Calculator",
        "answers": "Name 'AMAN G' written in silver permanent marker under battery cover.",
        "status": "PENDING",
        "admin_notes": None,
        "created_at": "2026-10-04T13:00:00",
        "reviewed_at": None
    }
]
