from typing import List, Dict, Any

SEED_USERS: List[Dict[str, Any]] = [
    {
        "user_id": "USR-ADMIN-01",
        "name": "Prof. S. K. Mehta (Chief Proctor)",
        "email": "admin@glbitm.ac.in",
        "password_hash": "admin123",
        "role": "ADMIN",
        "student_id": "FACULTY-GLB-01",
        "department": "Proctorial Board / Security",
        "semester": "Faculty & Staff",
        "phone": "+91 9876543299",
        "created_at": "2026-09-01T09:00:00"
    },
    {
        "user_id": "USR-STUDENT-01",
        "name": "Rahul Sharma",
        "email": "rahul.sharma@glbitm.ac.in",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100045",
        "department": "Computer Science & Engineering",
        "semester": "Semester 3",
        "phone": "+91 9876543210",
        "created_at": "2026-10-01T10:00:00"
    },
    {
        "user_id": "USR-STUDENT-02",
        "name": "Priya Verma",
        "email": "priya.verma@glbitm.ac.in",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100088",
        "department": "Information Technology",
        "semester": "Semester 3",
        "phone": "+91 9876543211",
        "created_at": "2026-10-02T11:30:00"
    },
    {
        "user_id": "USR-STUDENT-03",
        "name": "Aman Gupta",
        "email": "aman.gupta@glbitm.ac.in",
        "password_hash": "student123",
        "role": "STUDENT",
        "student_id": "2300970100112",
        "department": "Electronics & Communication",
        "semester": "Semester 5",
        "phone": "+91 9876543212",
        "created_at": "2026-10-03T12:00:00"
    }
]

SEED_IOT_BOXES: List[Dict[str, Any]] = [
    {
        "box_id": "BOX-001",
        "name": "GL Bajaj Central Library Smart Box",
        "location": "Central Library (Block A)",
        "status": "ONLINE",
        "last_seen": "2026-10-07T12:28:00",
        "items_registered": 14,
        "created_at": "2026-09-15T08:00:00"
    },
    {
        "box_id": "BOX-002",
        "name": "GL Bajaj Main Cafeteria Smart Box",
        "location": "Student Canteen",
        "status": "ONLINE",
        "last_seen": "2026-10-07T12:25:00",
        "items_registered": 8,
        "created_at": "2026-09-20T08:00:00"
    },
    {
        "box_id": "BOX-003",
        "name": "Audi Building & Placement Foyer Box",
        "location": "Audi Block",
        "status": "ONLINE",
        "last_seen": "2026-10-07T12:20:00",
        "items_registered": 4,
        "created_at": "2026-09-25T08:00:00"
    }
]

# 10 Realistic Lost Items for GL Bajaj
SEED_LOST_ITEMS: List[Dict[str, Any]] = [
    {
        "item_id": "LOST-0001",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@glbitm.ac.in",
        "student_id": "2300970100045",
        "item_name": "Leather Wallet with GL Bajaj ID",
        "category": "Wallet",
        "brand": "Wildhorn",
        "color": "Black",
        "description": "Black leather wallet with GL Bajaj student ID card lost near Central Library 1st floor reading hall.",
        "location": "Central Library (Block A)",
        "lost_at": "2026-10-06T13:30:00",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        "status": "LOST",
        "created_at": "2026-10-06T14:00:00"
    },
    {
        "item_id": "LOST-0002",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@glbitm.ac.in",
        "student_id": "2300970100088",
        "item_name": "Boat Wireless Earbuds",
        "category": "Electronics",
        "brand": "Boat",
        "color": "White",
        "description": "White Boat Airdopes wireless earbuds inside a black silicone protective case lost in Central Library desk.",
        "location": "Central Library (Block A)",
        "lost_at": "2026-10-05T14:30:00",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
        "status": "LOST",
        "created_at": "2026-10-05T15:00:00"
    },
    {
        "item_id": "LOST-0003",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@glbitm.ac.in",
        "student_id": "2300970100112",
        "item_name": "Scientific Calculator FX-991EX",
        "category": "Electronics",
        "brand": "Casio",
        "color": "Black",
        "description": "Casio FX-991EX ClassWiz calculator lost in Audi Block seminar hall row 4.",
        "location": "Audi Block",
        "lost_at": "2026-10-04T11:00:00",
        "image_url": "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400",
        "status": "LOST",
        "created_at": "2026-10-04T11:30:00"
    },
    {
        "item_id": "LOST-0004",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@glbitm.ac.in",
        "student_id": "2300970100045",
        "item_name": "Bike Keys with Leather Keychain",
        "category": "Keys",
        "brand": "Royal Enfield",
        "color": "Silver",
        "description": "Set of 3 keys with black Royal Enfield leather strap lost in GL Bajaj student canteen.",
        "location": "Student Canteen",
        "lost_at": "2026-10-03T16:00:00",
        "image_url": "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=400",
        "status": "LOST",
        "created_at": "2026-10-03T16:30:00"
    },
    {
        "item_id": "LOST-0005",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@glbitm.ac.in",
        "student_id": "2300970100088",
        "item_name": "Milton Insulated Bottle",
        "category": "Bottle",
        "brand": "Milton",
        "color": "Blue",
        "description": "Milton 1000ml blue stainless steel thermos bottle lost near basketball court.",
        "location": "Sports Ground",
        "lost_at": "2026-10-02T17:30:00",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        "status": "LOST",
        "created_at": "2026-10-02T18:00:00"
    },
    {
        "item_id": "LOST-0006",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@glbitm.ac.in",
        "student_id": "2300970100112",
        "item_name": "Smart Fitness Band",
        "category": "Watch",
        "brand": "Noise",
        "color": "Black",
        "description": "Noise ColorFit Pulse smart watch lost during sports period near ground.",
        "location": "Sports Ground",
        "lost_at": "2026-10-01T08:30:00",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        "status": "LOST",
        "created_at": "2026-10-01T09:00:00"
    },
    {
        "item_id": "LOST-0007",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@glbitm.ac.in",
        "student_id": "2300970100045",
        "item_name": "GL Bajaj College ID with Blue Lanyard",
        "category": "ID Card",
        "brand": "GL Bajaj ID",
        "color": "Blue",
        "description": "Student identity card of Rahul Sharma (Roll: 2300970100045) on GL Bajaj blue lanyard.",
        "location": "Main Entrance Gate #1",
        "lost_at": "2026-09-30T09:15:00",
        "image_url": "https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=400",
        "status": "LOST",
        "created_at": "2026-09-30T09:45:00"
    },
    {
        "item_id": "LOST-0008",
        "user_id": "USR-STUDENT-02",
        "user_name": "Priya Verma",
        "user_email": "priya.verma@glbitm.ac.in",
        "student_id": "2300970100088",
        "item_name": "Grey Laptop Backpack",
        "category": "Bag",
        "brand": "Skybags",
        "color": "Grey",
        "description": "Grey Skybags backpack containing semester notes and pen drive.",
        "location": "Lab Block C / Workshop",
        "lost_at": "2026-09-29T15:00:00",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "status": "LOST",
        "created_at": "2026-09-29T15:30:00"
    },
    {
        "item_id": "LOST-0009",
        "user_id": "USR-STUDENT-03",
        "user_name": "Aman Gupta",
        "user_email": "aman.gupta@glbitm.ac.in",
        "student_id": "2300970100112",
        "item_name": "SanDisk 64GB USB Drive",
        "category": "Electronics",
        "brand": "SanDisk",
        "color": "Red",
        "description": "Red SanDisk dual drive plugged into Computer Lab 3 terminal.",
        "location": "Central Library (Block A)",
        "lost_at": "2026-09-28T14:00:00",
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400",
        "status": "LOST",
        "created_at": "2026-09-28T14:30:00"
    },
    {
        "item_id": "LOST-0010",
        "user_id": "USR-STUDENT-01",
        "user_name": "Rahul Sharma",
        "user_email": "rahul.sharma@glbitm.ac.in",
        "student_id": "2300970100045",
        "item_name": "Data Structures Book (CLRS)",
        "category": "Books",
        "brand": "Pearson",
        "color": "Blue",
        "description": "Core algorithms textbook with handwritten sticky notes on 2nd floor library table.",
        "location": "Central Library (Block A)",
        "lost_at": "2026-09-27T17:00:00",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        "status": "LOST",
        "created_at": "2026-09-27T17:30:00"
    }
]

# 10 Realistic Found Items for GL Bajaj
SEED_FOUND_ITEMS: List[Dict[str, Any]] = [
    {
        "item_id": "FOUND-0001",
        "rfid_id": "RFID-1024",
        "box_id": "BOX-001",
        "item_name": "Black Leather Wallet",
        "category": "Wallet",
        "brand": "Wildhorn",
        "color": "Black",
        "description": "Black leather wallet containing college identity card found near Central Library 1st floor reading table.",
        "location": "Central Library (Block A)",
        "found_at": "2026-10-06T14:15:00",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-001 (Central Library)",
        "status": "FOUND",
        "created_at": "2026-10-06T14:15:00"
    },
    {
        "item_id": "FOUND-0002",
        "rfid_id": "RFID-E204A1",
        "box_id": "BOX-001",
        "item_name": "Boat Earbuds in Silicone Case",
        "category": "Electronics",
        "brand": "Boat",
        "color": "White",
        "description": "White Boat Airdopes wireless earbuds inside black silicone case discovered on 1st floor reading desk.",
        "location": "Central Library (Block A)",
        "found_at": "2026-10-05T15:10:00",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-001 (Central Library)",
        "status": "FOUND",
        "created_at": "2026-10-05T15:10:00"
    },
    {
        "item_id": "FOUND-0003",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Casio Scientific Calculator FX-991EX",
        "category": "Electronics",
        "brand": "Casio",
        "color": "Black",
        "description": "Casio FX991EX ClassWiz scientific calculator found in Audi Block seminar hall.",
        "location": "Audi Block",
        "found_at": "2026-10-04T12:00:00",
        "image_url": "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-02",
        "reported_by_name": "Priya Verma",
        "status": "FOUND",
        "created_at": "2026-10-04T12:00:00"
    },
    {
        "item_id": "FOUND-0004",
        "rfid_id": "RFID-KEY-88",
        "box_id": "BOX-002",
        "item_name": "Bike Keys with Leather Tag",
        "category": "Keys",
        "brand": "Royal Enfield",
        "color": "Silver",
        "description": "Three motorcycle keys on a Royal Enfield branded leather strap found at canteen table.",
        "location": "Student Canteen",
        "found_at": "2026-10-03T16:45:00",
        "image_url": "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=400",
        "source": "IOT",
        "reported_by_id": None,
        "reported_by_name": "BOX-002 (Main Canteen)",
        "status": "FOUND",
        "created_at": "2026-10-03T16:45:00"
    },
    {
        "item_id": "FOUND-0005",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Blue Insulated Bottle",
        "category": "Bottle",
        "brand": "Milton",
        "color": "Blue",
        "description": "Milton blue steel thermos water bottle found in sports ground seating bench.",
        "location": "Sports Ground",
        "found_at": "2026-10-02T18:15:00",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-01",
        "reported_by_name": "Rahul Sharma",
        "status": "FOUND",
        "created_at": "2026-10-02T18:15:00"
    },
    {
        "item_id": "FOUND-0006",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Black Fitness Smartwatch",
        "category": "Watch",
        "brand": "Noise",
        "color": "Black",
        "description": "Noise ColorFit Pulse black digital fitness band found on gym floor near sports ground.",
        "location": "Sports Ground",
        "found_at": "2026-10-01T09:30:00",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-03",
        "reported_by_name": "Aman Gupta",
        "status": "FOUND",
        "created_at": "2026-10-01T09:30:00"
    },
    {
        "item_id": "FOUND-0007",
        "rfid_id": None,
        "box_id": None,
        "item_name": "GL Bajaj ID Badge with Blue Lanyard",
        "category": "ID Card",
        "brand": "GL Bajaj ID",
        "color": "Blue",
        "description": "Student identity card on blue strap dropped near security cabin at Main Entrance Gate #1.",
        "location": "Main Entrance Gate #1",
        "found_at": "2026-09-30T10:00:00",
        "image_url": "https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Security Guard Post #1",
        "status": "FOUND",
        "created_at": "2026-09-30T10:00:00"
    },
    {
        "item_id": "FOUND-0008",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Grey Laptop Bag",
        "category": "Bag",
        "brand": "Skybags",
        "color": "Grey",
        "description": "Skybags grey backpack found on desk row 3 in Lab Block C.",
        "location": "Lab Block C / Workshop",
        "found_at": "2026-09-29T16:00:00",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-STUDENT-02",
        "reported_by_name": "Priya Verma",
        "status": "FOUND",
        "created_at": "2026-09-29T16:00:00"
    },
    {
        "item_id": "FOUND-0009",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Red 64GB Flash Drive",
        "category": "Electronics",
        "brand": "SanDisk",
        "color": "Red",
        "description": "SanDisk Dual USB pendrive plugged into library computer terminal 8.",
        "location": "Central Library (Block A)",
        "found_at": "2026-09-28T15:00:00",
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Library Staff",
        "status": "FOUND",
        "created_at": "2026-09-28T15:00:00"
    },
    {
        "item_id": "FOUND-0010",
        "rfid_id": None,
        "box_id": None,
        "item_name": "Algorithms Computer Science Textbook",
        "category": "Books",
        "brand": "Pearson",
        "color": "Blue",
        "description": "Introduction to Algorithms book found on 2nd floor library table.",
        "location": "Central Library (Block A)",
        "found_at": "2026-09-27T18:00:00",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        "source": "MANUAL",
        "reported_by_id": "USR-ADMIN-01",
        "reported_by_name": "Library Staff",
        "status": "FOUND",
        "created_at": "2026-09-27T18:00:00"
    }
]

SEED_CLAIMS: List[Dict[str, Any]] = [
    {
        "claim_id": "CLM-001",
        "user_id": "USR-STUDENT-01",
        "student_name": "Rahul Sharma",
        "student_email": "rahul.sharma@glbitm.ac.in",
        "student_id": "2300970100045",
        "lost_item_id": "LOST-0001",
        "found_item_id": "FOUND-0001",
        "item_name": "Black Leather Wallet",
        "answers": "Contains GL Bajaj student ID with roll 2300970100045, one metro card, and ₹350 cash inside coin pocket.",
        "status": "PENDING",
        "admin_notes": None,
        "created_at": "2026-10-06T15:00:00",
        "reviewed_at": None
    },
    {
        "claim_id": "CLM-002",
        "user_id": "USR-STUDENT-02",
        "student_name": "Priya Verma",
        "student_email": "priya.verma@glbitm.ac.in",
        "student_id": "2300970100088",
        "lost_item_id": "LOST-0002",
        "found_item_id": "FOUND-0002",
        "item_name": "Boat Wireless Earbuds",
        "answers": "Small cat sticker on top of the black silicone case, serial starts with BT-88.",
        "status": "PENDING",
        "admin_notes": None,
        "created_at": "2026-10-05T16:00:00",
        "reviewed_at": None
    }
]
